import React from 'react'
import { Col } from 'react-bootstrap'

export default ({ match }) => (
  <Col sm={9} md={10} smOffset={3} mdOffset={2} className="main">

    <h1>{match.path}</h1>
    <hr />
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed porttitor sapien vitae justo cursus, quis ultrices urna convallis. Proin sagittis ipsum eros, at posuere lorem eleifend vitae. Proin pellentesque pharetra ex, vel sollicitudin mi feugiat non. Suspendisse gravida ligula at massa consequat pulvinar. Quisque consequat ac lacus eu efficitur. Sed eu ultrices lectus. Curabitur non venenatis mauris. Vivamus non viverra dui, nec tempor est. Fusce bibendum, mi non viverra ultrices, lorem enim blandit odio, ut tempor ligula lacus vitae mi.</p>
    <p>Pellentesque pretium orci purus, vitae eleifend mi cursus at. Maecenas facilisis nisi vitae bibendum tempus. Curabitur sed lobortis quam. Sed a urna lacus. Sed mattis at felis non varius. Donec diam odio, convallis non fringilla ac, bibendum vel justo. Ut et diam id enim maximus consequat. Quisque commodo leo enim, in porttitor ligula faucibus ac. Proin euismod nulla vel massa semper, a ultrices augue porta. Suspendisse aliquet elit ac nibh blandit, ac fringilla risus interdum. Nunc mattis justo vel quam blandit tristique a quis diam. Proin ligula ante, rhoncus non egestas et, consectetur in massa. Quisque justo diam, euismod eu porttitor sed, vestibulum vitae ante. Suspendisse non purus urna.</p>
    <p>In accumsan nunc at rhoncus ultrices. Pellentesque at orci porta, fringilla tortor nec, faucibus mauris. Integer hendrerit eget justo ut sodales. Phasellus sollicitudin dolor eget nunc auctor fermentum. Curabitur ultrices fringilla arcu sit amet posuere. Sed molestie porttitor gravida. Nam convallis a quam ut convallis. Maecenas sed tincidunt urna. Proin suscipit eleifend mi, lobortis posuere velit molestie eu. Morbi faucibus magna erat, nec dictum tortor efficitur nec. Suspendisse at molestie lectus. Mauris ac ipsum magna.</p>
    <p>Cras porta sed enim nec varius. Quisque vitae auctor enim. Cras eget ultrices quam, vitae laoreet massa. Donec et purus ligula. Quisque dignissim nulla id magna porttitor, in laoreet risus feugiat. Morbi congue augue mi, ut lobortis quam convallis nec. Duis at justo nisl. Nunc eu hendrerit ligula. Nulla quis turpis ac diam sagittis elementum. Fusce id arcu metus. Praesent eu risus consequat, fringilla quam ac, sollicitudin libero. Donec at cursus purus. Ut ut purus lacinia, volutpat urna vel, tristique est. Sed at ipsum magna. Phasellus vulputate augue mi, vitae sagittis nulla euismod non.</p>
    <p>In mattis egestas ante quis luctus. Nunc vel quam tincidunt, laoreet justo vel, cursus est. Phasellus et orci gravida, ultricies massa sed, imperdiet quam. Nunc aliquet placerat elit, at ultricies mauris gravida non. Integer non orci odio. Quisque massa ante, accumsan eget elit quis, efficitur euismod enim. Maecenas in hendrerit nunc. Praesent vitae metus odio.</p>

    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed porttitor sapien vitae justo cursus, quis ultrices urna convallis. Proin sagittis ipsum eros, at posuere lorem eleifend vitae. Proin pellentesque pharetra ex, vel sollicitudin mi feugiat non. Suspendisse gravida ligula at massa consequat pulvinar. Quisque consequat ac lacus eu efficitur. Sed eu ultrices lectus. Curabitur non venenatis mauris. Vivamus non viverra dui, nec tempor est. Fusce bibendum, mi non viverra ultrices, lorem enim blandit odio, ut tempor ligula lacus vitae mi.</p>
    <p>Pellentesque pretium orci purus, vitae eleifend mi cursus at. Maecenas facilisis nisi vitae bibendum tempus. Curabitur sed lobortis quam. Sed a urna lacus. Sed mattis at felis non varius. Donec diam odio, convallis non fringilla ac, bibendum vel justo. Ut et diam id enim maximus consequat. Quisque commodo leo enim, in porttitor ligula faucibus ac. Proin euismod nulla vel massa semper, a ultrices augue porta. Suspendisse aliquet elit ac nibh blandit, ac fringilla risus interdum. Nunc mattis justo vel quam blandit tristique a quis diam. Proin ligula ante, rhoncus non egestas et, consectetur in massa. Quisque justo diam, euismod eu porttitor sed, vestibulum vitae ante. Suspendisse non purus urna.</p>
    <p>In accumsan nunc at rhoncus ultrices. Pellentesque at orci porta, fringilla tortor nec, faucibus mauris. Integer hendrerit eget justo ut sodales. Phasellus sollicitudin dolor eget nunc auctor fermentum. Curabitur ultrices fringilla arcu sit amet posuere. Sed molestie porttitor gravida. Nam convallis a quam ut convallis. Maecenas sed tincidunt urna. Proin suscipit eleifend mi, lobortis posuere velit molestie eu. Morbi faucibus magna erat, nec dictum tortor efficitur nec. Suspendisse at molestie lectus. Mauris ac ipsum magna.</p>
    <p>Cras porta sed enim nec varius. Quisque vitae auctor enim. Cras eget ultrices quam, vitae laoreet massa. Donec et purus ligula. Quisque dignissim nulla id magna porttitor, in laoreet risus feugiat. Morbi congue augue mi, ut lobortis quam convallis nec. Duis at justo nisl. Nunc eu hendrerit ligula. Nulla quis turpis ac diam sagittis elementum. Fusce id arcu metus. Praesent eu risus consequat, fringilla quam ac, sollicitudin libero. Donec at cursus purus. Ut ut purus lacinia, volutpat urna vel, tristique est. Sed at ipsum magna. Phasellus vulputate augue mi, vitae sagittis nulla euismod non.</p>
    <p>In mattis egestas ante quis luctus. Nunc vel quam tincidunt, laoreet justo vel, cursus est. Phasellus et orci gravida, ultricies massa sed, imperdiet quam. Nunc aliquet placerat elit, at ultricies mauris gravida non. Integer non orci odio. Quisque massa ante, accumsan eget elit quis, efficitur euismod enim. Maecenas in hendrerit nunc. Praesent vitae metus odio.</p>

    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed porttitor sapien vitae justo cursus, quis ultrices urna convallis. Proin sagittis ipsum eros, at posuere lorem eleifend vitae. Proin pellentesque pharetra ex, vel sollicitudin mi feugiat non. Suspendisse gravida ligula at massa consequat pulvinar. Quisque consequat ac lacus eu efficitur. Sed eu ultrices lectus. Curabitur non venenatis mauris. Vivamus non viverra dui, nec tempor est. Fusce bibendum, mi non viverra ultrices, lorem enim blandit odio, ut tempor ligula lacus vitae mi.</p>
    <p>Pellentesque pretium orci purus, vitae eleifend mi cursus at. Maecenas facilisis nisi vitae bibendum tempus. Curabitur sed lobortis quam. Sed a urna lacus. Sed mattis at felis non varius. Donec diam odio, convallis non fringilla ac, bibendum vel justo. Ut et diam id enim maximus consequat. Quisque commodo leo enim, in porttitor ligula faucibus ac. Proin euismod nulla vel massa semper, a ultrices augue porta. Suspendisse aliquet elit ac nibh blandit, ac fringilla risus interdum. Nunc mattis justo vel quam blandit tristique a quis diam. Proin ligula ante, rhoncus non egestas et, consectetur in massa. Quisque justo diam, euismod eu porttitor sed, vestibulum vitae ante. Suspendisse non purus urna.</p>
    <p>In accumsan nunc at rhoncus ultrices. Pellentesque at orci porta, fringilla tortor nec, faucibus mauris. Integer hendrerit eget justo ut sodales. Phasellus sollicitudin dolor eget nunc auctor fermentum. Curabitur ultrices fringilla arcu sit amet posuere. Sed molestie porttitor gravida. Nam convallis a quam ut convallis. Maecenas sed tincidunt urna. Proin suscipit eleifend mi, lobortis posuere velit molestie eu. Morbi faucibus magna erat, nec dictum tortor efficitur nec. Suspendisse at molestie lectus. Mauris ac ipsum magna.</p>
    <p>Cras porta sed enim nec varius. Quisque vitae auctor enim. Cras eget ultrices quam, vitae laoreet massa. Donec et purus ligula. Quisque dignissim nulla id magna porttitor, in laoreet risus feugiat. Morbi congue augue mi, ut lobortis quam convallis nec. Duis at justo nisl. Nunc eu hendrerit ligula. Nulla quis turpis ac diam sagittis elementum. Fusce id arcu metus. Praesent eu risus consequat, fringilla quam ac, sollicitudin libero. Donec at cursus purus. Ut ut purus lacinia, volutpat urna vel, tristique est. Sed at ipsum magna. Phasellus vulputate augue mi, vitae sagittis nulla euismod non.</p>
    <p>In mattis egestas ante quis luctus. Nunc vel quam tincidunt, laoreet justo vel, cursus est. Phasellus et orci gravida, ultricies massa sed, imperdiet quam. Nunc aliquet placerat elit, at ultricies mauris gravida non. Integer non orci odio. Quisque massa ante, accumsan eget elit quis, efficitur euismod enim. Maecenas in hendrerit nunc. Praesent vitae metus odio.</p>

    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed porttitor sapien vitae justo cursus, quis ultrices urna convallis. Proin sagittis ipsum eros, at posuere lorem eleifend vitae. Proin pellentesque pharetra ex, vel sollicitudin mi feugiat non. Suspendisse gravida ligula at massa consequat pulvinar. Quisque consequat ac lacus eu efficitur. Sed eu ultrices lectus. Curabitur non venenatis mauris. Vivamus non viverra dui, nec tempor est. Fusce bibendum, mi non viverra ultrices, lorem enim blandit odio, ut tempor ligula lacus vitae mi.</p>
    <p>Pellentesque pretium orci purus, vitae eleifend mi cursus at. Maecenas facilisis nisi vitae bibendum tempus. Curabitur sed lobortis quam. Sed a urna lacus. Sed mattis at felis non varius. Donec diam odio, convallis non fringilla ac, bibendum vel justo. Ut et diam id enim maximus consequat. Quisque commodo leo enim, in porttitor ligula faucibus ac. Proin euismod nulla vel massa semper, a ultrices augue porta. Suspendisse aliquet elit ac nibh blandit, ac fringilla risus interdum. Nunc mattis justo vel quam blandit tristique a quis diam. Proin ligula ante, rhoncus non egestas et, consectetur in massa. Quisque justo diam, euismod eu porttitor sed, vestibulum vitae ante. Suspendisse non purus urna.</p>
    <p>In accumsan nunc at rhoncus ultrices. Pellentesque at orci porta, fringilla tortor nec, faucibus mauris. Integer hendrerit eget justo ut sodales. Phasellus sollicitudin dolor eget nunc auctor fermentum. Curabitur ultrices fringilla arcu sit amet posuere. Sed molestie porttitor gravida. Nam convallis a quam ut convallis. Maecenas sed tincidunt urna. Proin suscipit eleifend mi, lobortis posuere velit molestie eu. Morbi faucibus magna erat, nec dictum tortor efficitur nec. Suspendisse at molestie lectus. Mauris ac ipsum magna.</p>
    <p>Cras porta sed enim nec varius. Quisque vitae auctor enim. Cras eget ultrices quam, vitae laoreet massa. Donec et purus ligula. Quisque dignissim nulla id magna porttitor, in laoreet risus feugiat. Morbi congue augue mi, ut lobortis quam convallis nec. Duis at justo nisl. Nunc eu hendrerit ligula. Nulla quis turpis ac diam sagittis elementum. Fusce id arcu metus. Praesent eu risus consequat, fringilla quam ac, sollicitudin libero. Donec at cursus purus. Ut ut purus lacinia, volutpat urna vel, tristique est. Sed at ipsum magna. Phasellus vulputate augue mi, vitae sagittis nulla euismod non.</p>
    <p>In mattis egestas ante quis luctus. Nunc vel quam tincidunt, laoreet justo vel, cursus est. Phasellus et orci gravida, ultricies massa sed, imperdiet quam. Nunc aliquet placerat elit, at ultricies mauris gravida non. Integer non orci odio. Quisque massa ante, accumsan eget elit quis, efficitur euismod enim. Maecenas in hendrerit nunc. Praesent vitae metus odio.</p>

    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed porttitor sapien vitae justo cursus, quis ultrices urna convallis. Proin sagittis ipsum eros, at posuere lorem eleifend vitae. Proin pellentesque pharetra ex, vel sollicitudin mi feugiat non. Suspendisse gravida ligula at massa consequat pulvinar. Quisque consequat ac lacus eu efficitur. Sed eu ultrices lectus. Curabitur non venenatis mauris. Vivamus non viverra dui, nec tempor est. Fusce bibendum, mi non viverra ultrices, lorem enim blandit odio, ut tempor ligula lacus vitae mi.</p>
    <p>Pellentesque pretium orci purus, vitae eleifend mi cursus at. Maecenas facilisis nisi vitae bibendum tempus. Curabitur sed lobortis quam. Sed a urna lacus. Sed mattis at felis non varius. Donec diam odio, convallis non fringilla ac, bibendum vel justo. Ut et diam id enim maximus consequat. Quisque commodo leo enim, in porttitor ligula faucibus ac. Proin euismod nulla vel massa semper, a ultrices augue porta. Suspendisse aliquet elit ac nibh blandit, ac fringilla risus interdum. Nunc mattis justo vel quam blandit tristique a quis diam. Proin ligula ante, rhoncus non egestas et, consectetur in massa. Quisque justo diam, euismod eu porttitor sed, vestibulum vitae ante. Suspendisse non purus urna.</p>
    <p>In accumsan nunc at rhoncus ultrices. Pellentesque at orci porta, fringilla tortor nec, faucibus mauris. Integer hendrerit eget justo ut sodales. Phasellus sollicitudin dolor eget nunc auctor fermentum. Curabitur ultrices fringilla arcu sit amet posuere. Sed molestie porttitor gravida. Nam convallis a quam ut convallis. Maecenas sed tincidunt urna. Proin suscipit eleifend mi, lobortis posuere velit molestie eu. Morbi faucibus magna erat, nec dictum tortor efficitur nec. Suspendisse at molestie lectus. Mauris ac ipsum magna.</p>
    <p>Cras porta sed enim nec varius. Quisque vitae auctor enim. Cras eget ultrices quam, vitae laoreet massa. Donec et purus ligula. Quisque dignissim nulla id magna porttitor, in laoreet risus feugiat. Morbi congue augue mi, ut lobortis quam convallis nec. Duis at justo nisl. Nunc eu hendrerit ligula. Nulla quis turpis ac diam sagittis elementum. Fusce id arcu metus. Praesent eu risus consequat, fringilla quam ac, sollicitudin libero. Donec at cursus purus. Ut ut purus lacinia, volutpat urna vel, tristique est. Sed at ipsum magna. Phasellus vulputate augue mi, vitae sagittis nulla euismod non.</p>
    <p>In mattis egestas ante quis luctus. Nunc vel quam tincidunt, laoreet justo vel, cursus est. Phasellus et orci gravida, ultricies massa sed, imperdiet quam. Nunc aliquet placerat elit, at ultricies mauris gravida non. Integer non orci odio. Quisque massa ante, accumsan eget elit quis, efficitur euismod enim. Maecenas in hendrerit nunc. Praesent vitae metus odio.</p>
  </Col>
);
